apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <name>
  region: <region>

vpc: # Optional
  subnets:
    Private:
      us-west-1a:
        id: ""
      us-west-1c:
        id: ""



managedNodeGroups:
- name: standard-workers
  instanceType: t2.micro
  desiredCapacity: 5
  minSize: 2
  maxSize: 10

